baseURL = "https://thiswastomorrow.co.uk/"
languageCode = "en-gb"
title = "This Was Tomorrow"

[params]
  description = "Site Visit Archive"
  author = "Enrico Policardo"
  email = "info@enricopolicardo.com"
  phone = "+44(0)7517 420 206"
  tagline = "Is This the Future We Were Dreaming Of?"
  footer_project = "A photographic investigation by Enrico Policardo into community-led housing across the UK."
  footer_credit = "This Was Tomorrow is supported by Arts Council England (DYCP)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
