baseURL = "https://cardopoli.github.io/this-was-tomorrow/"
languageCode = "en-gb"
title = "This Was Tomorrow"
theme = ""

[params]
  description = "Site Visit Archive"
  author = "Enrico Policardo"
  email = "info@enricopolicardo.com"
  phone = "+44(0)7517 420 206"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
